Implement NavHpPosEcef message and PositionECEF
ublox-rs/ublox pull request #74
Opened 2023-11-30 18:41 UTC by LarsJaeger

The message has been implemented according to [this datasheet](https://cdn.sparkfun.com/assets/f/7/4/3/5/PM-15136.pdf#page=157&zoom=100,0,338).
The type has been implemented analog to PositionLLH.

2023-11-30 23:01 UTC, gwbres requested changes

2023-11-30 23:01 UTC, gwbres commented on ublox/src/ubx_packets/types.rs
> +    pub x: f64,
Hello,
the proposed documentation is wrong: these are ECEF coordinates not Longitude Latitude angles nor Altitude (as you correctly defined in `NavHpPosEcef`)

2023-11-30 23:01 UTC, gwbres commented on ublox/src/ubx_packets/types.rs
> +    /// Latitude in degrees
y coordinates

2023-11-30 23:01 UTC, gwbres commented on ublox/src/ubx_packets/types.rs
> +    /// Altitude in meters
z coordinates

2023-12-01 09:26 UTC, LarsJaeger commented
Sorry, must have forgotten to change the documentation when I copied from PositionLLH  ^^. Should be fixed with my most recent commit. Please let me know if there are other issues, never before have I done anything in rust :innocent: .

2023-12-01 09:27 UTC, LarsJaeger commented on ublox/src/ubx_packets/types.rs
> +    /// Latitude in degrees
updated in latest commit

2023-12-01 09:48 UTC, gwbres approved these changes

2023-12-01 09:48 UTC, merged